[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  EMAIL_USER = "oneplu12@gmail.com"
  EMAIL_PASS = "fegu hgmx mbgs yykn"
  RECAPTCHA_SECRET_KEY = "YOUR_RECAPTCHA_SECRET_KEY"

